### ISSUE TITLE
Bond Reader repo missing?

### ISSUE THREAD

**Issue by DerrikCreates** [dend/dend#1]
sorry to leave ask this here but i cannot find any other place to contact you directly and your about me mentioned to contact you on projects you maintain but the project is missing. Im looking for the Bond Reader app you made last year and cannot find the actual repo to this project anywhere. Do you have a link to the project? Im also creating a halo infinite related [stat tracking site](https://forgetracker.com) and would like to have a link back to this pretty important tool. Thanks

**Comment by dend** [comment]
Hey @DerrikCreates - the repository and the tool are no longer available, unfortunately. Your best starting point is the [official Bond project website](https://microsoft.github.io/bond/manual/bond_cs.html).

**Comment by forresthopkinsa** [comment]
I have a similar question about the Foggycam Experimental Branch mentioned [here](https://den.dev/blog/free-nest-video-recording/), do you know if there's any archive where this code can be found?
